# Development environment configuration
extends: base.yaml

name: "data-pipeline-dev"

logging:
  level: DEBUG
  handlers:
    console: true
    file: true
    file_path: "./logs/development.log"

database:
  host: localhost
  port: 5432
  database: myapp_db
  username: jacob
  password: ""
  pool_size: 10
  max_overflow: 20
  echo: true

storage:
  local:
    base_path: "./data"
  
processing:
  memory_limit_gb: 4
  spark:
    master: "local[2]"
    config:
      "spark.sql.adaptive.enabled": "true"
      "spark.driver.memory": "2g"
      "spark.executor.memory": "2g"

validation:
  fail_on_error: true

monitoring:
  enabled: false